# Generated by Django 5.0.2 on 2024-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_data',
            name='json_file',
            field=models.FileField(upload_to='chat/'),
        ),
    ]
