# Generated by Django 4.2.11 on 2024-03-07 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_chat', '0004_remove_message_reciever_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
